# Generated by Django 5.2.1 on 2025-05-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='mode',
            field=models.CharField(choices=[('blitz', 'Blitz'), ('rapid', 'Rápido'), ('classical', 'Clásico'), ('bullet', 'Bullet')], default='rapid', max_length=20),
        ),
    ]
