# Generated by Django 5.2.1 on 2025-05-23 02:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Curso'), ('finished', 'Finalizada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('result', models.CharField(choices=[('white_wins', 'Ganan Blancas'), ('black_wins', 'Ganan Negras'), ('draw', 'Empate'), ('pending', 'Pendiente')], default='pending', max_length=20)),
                ('round_number', models.IntegerField(default=1)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('moves', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_matches', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['-created_at'],
            },
        ),
    ]
